name: CI
on: 
  push:
    branches: [ main ]
jobs:
  satu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u nodespod -p Danang-112
      - run: docker build . -t nodespod/ae:1
      - run: docker push nodespod/ae:1
