name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          chmod +x judul-manga
          ./judul-manga
          git config --local user.email " chriskm0116@gmail.com"
          git config --local user.name " Arlentak"
          git add -A
          git commit -m "Add $RANDOM $TTT"
          git push
